name: ESLint Check

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run ESLint check (default)
      - name: Run ESLint (check only)
        run: npm run lint
       
      # 🔹 Optional: Auto-fix issues (currently Enable)
      - name: Run ESLint (auto-fix)
        run: npm run lint:fix 