name: Prettier Format Check

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Prettier Check (default)
        run: npx prettier --check .

      # 🔹 Optional: Auto-format (currently enable)
      - name: Run Prettier Auto-Format
        run: npx prettier --write .
